code --install-extension smobile.vscode-appcenter
code --install-extension ms-vscode.azure-account
code --install-extension rebornix.ruby
code --install-extension ms-azure-devops.azure-pipelines
code --install-extension ms-vsts.team
code --install-extension dnicolson.binary-plist
code --install-extension agenric.cocoapods-snippets
code --install-extension docsmsft.docs-yaml
code --install-extension fivethree.vscode-fastlane-snippets
code --install-extension orta.vscode-ios-common-files
code --install-extension pbeast.lanes-navigator
code --install-extension zhouronghui.propertylist
code --install-extension oxundermoon.shell-format
code --install-extension wingrunr21.vscode-ruby
code --install-extension mhcpnl.xcodestrings
code --install-extension redhat.vscode-yaml
code --install-extension stevemoser.xcode-keybindings
code --install-extension mariomatheu.syntax-project-pbxproj
code --install-extension mohsen1.prettify-json
code --install-extension vscode-icons-team.vscode-icons